global:
  name: consul
  datacenter: dc-1
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: true
  grpc: true
ui:
  enabled: true
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
  service:
    type: LoadBalancer
connectInject:
  enabled: true
  default: true
  metrics:
    defaultEnableMerging: true ## to enable the metrics in consul
controller:
  enabled: true
  centralConfig:
    enabled: true
    defaultProtocol: "http"
meshGateway:
  enabled: true
ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
terminatingGateways:
  enabled: true
  gateways:
    - name: terminating-gateway
  tests:
    - enabled: false
